@baseUrl = http://localhost:3000

### --- LIBROS ---

### Listar todos
GET {{baseUrl}}/api/libros

### Listar solo destacados
GET {{baseUrl}}/api/libros?destacado=true

### Ver un libro existente
GET {{baseUrl}}/api/libros/1

### Ver libro que NO existe (404)
GET {{baseUrl}}/api/libros/999

### Crear libro (201)
POST {{baseUrl}}/api/libros
Content-Type: application/json

{
  "titulo": "Rayuela",
  "autor": "Julio Cortázar",
  "precio": 7000,
  "imagen": "url",
  "destacado": true
}

### Editar libro (200)
PUT {{baseUrl}}/api/libros/1
Content-Type: application/json

{
  "precio": 99999
}

### Borrar libro (204)
DELETE {{baseUrl}}/api/libros/1


### --- AUTORES ---

### Listar autores
GET {{baseUrl}}/api/autores

### Ver autor inexistente (404)
GET {{baseUrl}}/api/autores/999

### Crear autor (201)
POST {{baseUrl}}/api/autores
Content-Type: application/json

{
  "nombre": "Jorge Luis Borges",
  "nacionalidad": "Argentina"
}